name: 'Terraform CI/CD with Quality Checks'

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Setup Terragrunt
        run: |
          curl -L -o terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.0/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Install checkov
        run: pip install checkov

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run tflint (in dev folder)
        run: |
          cd dev
          tflint --init
          tflint -f compact

      - name: Run checkov (in dev folder)
        run: |
          cd dev
          checkov -d . --quiet

      - name: Terraform Validate
        run: |
          export TF_SKIP_PROVIDER_VERIFY=1
          cd dev
          terragrunt run-all validate

      - name: Terragrunt Plan (on Pull Request)
        if: github.event_name == 'pull_request'
        run: |
          cd dev
          terragrunt plan -out=tfplan

      #- name: Terragrunt Apply (on push to master/main)
       # if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        #run: |
         # cd dev
          #terragrunt apply -auto-approve